services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./projects:/app/projects
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend